ALTER TABLE auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('auth_group', 'id'), (SELECT MAX(id) FROM auth_group));

ALTER TABLE auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('auth_group_permissions', 'id'), (SELECT MAX(id) FROM auth_group_permissions));

ALTER TABLE auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('auth_permission', 'id'), (SELECT MAX(id) FROM auth_permission));

ALTER TABLE django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('django_admin_log', 'id'), (SELECT MAX(id) FROM django_admin_log));

ALTER TABLE django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('django_content_type', 'id'), (SELECT MAX(id) FROM django_content_type));

ALTER TABLE django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('django_migrations', 'id'), (SELECT MAX(id) FROM django_migrations));

ALTER TABLE posts_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('posts_comment', 'id'), (SELECT MAX(id) FROM posts_comment));

ALTER TABLE posts_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('posts_post', 'id'), (SELECT MAX(id) FROM posts_post));

ALTER TABLE posts_post_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('posts_post_tags', 'id'), (SELECT MAX(id) FROM posts_post_tags));

ALTER TABLE posts_reaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('posts_reaction', 'id'), (SELECT MAX(id) FROM posts_reaction));

ALTER TABLE posts_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('posts_tag', 'id'), (SELECT MAX(id) FROM posts_tag));

ALTER TABLE token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('token_blacklist_blacklistedtoken', 'id'), (SELECT MAX(id) FROM token_blacklist_blacklistedtoken));

ALTER TABLE token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('token_blacklist_outstandingtoken', 'id'), (SELECT MAX(id) FROM token_blacklist_outstandingtoken));

ALTER TABLE users_passwordresettoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('users_passwordresettoken', 'id'), (SELECT MAX(id) FROM users_passwordresettoken));

ALTER TABLE users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('users_user', 'id'), (SELECT MAX(id) FROM users_user));

ALTER TABLE users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('users_user_groups', 'id'), (SELECT MAX(id) FROM users_user_groups));

ALTER TABLE users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('users_user_user_permissions', 'id'), (SELECT MAX(id) FROM users_user_user_permissions));